apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: group1-ippool
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: group == "group1"
  
---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: group2-ippool
spec:
  cidr: 192.168.2.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: group == "group2"